### ISSUE TITLE
"API Key can not be blank" error when generating cookie

### ISSUE THREAD

**Issue by SamG92** [d-suter/datadome-bp#1]
Hello,

Thanks for sharing the code. I tried to run it and it says "Successfully created a cookie for https://www.seloger.com" but I get a wrong body response with body {"raw":"I Key can not be blank","cookie":"I Key can not be blank"} (datadome response is "API Key can not be blank")

Do you have an idea why?

Thanks a lot
Alex

**Comment by d-suter** [comment]
Hello!

I believe the datadome bp has been patched and is no longer working. This is probably the reason why you are getting an error
